
#ifndef CLEAFIRYSAYS_H
#define CLEAFIRYSAYS_H

#include <iostream>
#include <vector>
#include <cstdlib>   // For rand(), srand()
#include <ctime>     // For time()
#include <cctype>    // For toupper()
#include <limits>    // For clearing input buffer
#include <string>
#include <fstream>   // For file handling
#include <sstream>   // For string parsing
#include <stdexcept> // For error handling

namespace ClefairyGame {

    // Shorten standard namespace usage
    using std::cout;
    using std::cin;
    using std::endl;
    using std::vector;
    using std::string;

    // Structure to store player data
    struct Player {
        string name;
        int score;
    };

    // Clears the screen depending on the operating system
    void clearScreen() {
        #ifdef _WIN32
            system("cls");
        #else
            system("clear");
        #endif
    }

    // Generates a random direction key: W, A, S, or D
    char generateRandomKey() {
        const char keys[] = {'W', 'A', 'S', 'D'};
        return keys[rand() % 4];
    }

    // Displays the arrow corresponding to the given key
    void showArrow(char arrow) {
        switch (arrow) {
            case 'W': cout << "↑ (W)" << endl; break;
            case 'A': cout << "← (A)" << endl; break;
            case 'S': cout << "↓ (S)" << endl; break;
            case 'D': cout << "→ (D)" << endl; break;
            default:  cout << "?" << endl; break;
        }
    }

    // Waits for the user to press ENTER
    void waitForEnter() {
        cout << "\nPress ENTER to continue...";
        cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
    }

    // Checks whether the given character is a valid key
    bool isValidKey(char c) {
        c = toupper(c);
        return c == 'W' || c == 'A' || c == 'S' || c == 'D';
    }

    // Saves the player's score to the "scores.txt" file
    void saveScore(const Player& player) {
        try {
            std::ofstream outFile("scores.txt", std::ios::app);
            if (!outFile) {
                throw std::runtime_error("Unable to open scores.txt for writing.");
            }
            outFile << player.name << "," << player.score << "\n";
            outFile.close();
        } catch (const std::exception& e) {
            std::cerr << "⚠️ Error saving score: " << e.what() << endl;
        }
    }

    // Displays all saved high scores from the file
    void showHighScores() {
        std::ifstream inFile("scores.txt");
        string line;

        cout << "\n High Scores:\n";
        cout << "----------------------\n";

        // If the file doesn't exist, create it and notify the user
        if (!inFile) {
            std::ofstream createFile("scores.txt"); // Creates the file
            createFile.close();
            cout << "(No scores yet!)\n";
            cout << "----------------------\n\n";
            return;
        }

        // Read and display each line from the file
        while (getline(inFile, line)) {
            std::istringstream iss(line);
            string name, score;
            if (getline(iss, name, ',') && getline(iss, score)) {
                cout << name << " - " << score << endl;
            }
        }

        inFile.close();
        cout << "----------------------\n\n";
    }

    // Main game logic for "Clefairy Says"
    void playClefairySays() {
        // Initialize random seed
        srand(static_cast<unsigned int>(time(0)));

        Player player;
        vector<char> sequence;      // Sequence generated by the game
        vector<char> playerInput;   // Sequence entered by the player
        int level = 1;              // Current level
        bool playing = true;       // Game state

        // Welcome and instructions
        cout << " Welcome to 'Clefairy Says'!\n";
        showHighScores();

        // Ask for the player's name
        cout << "Enter your name: ";
        getline(cin, player.name);

        // Game instructions
        cout << "Repeat the sequence using W (^), A (<), S (v), D (>)\n";
        cout << "Press ENTER to start...\n";
        cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');

        clearScreen();

        // Main game loop
        while (playing) {
            // Add a new random direction to the sequence
            sequence.push_back(generateRandomKey());

            // Display the full sequence one arrow at a time
            for (char arrow : sequence) {
                clearScreen();
                cout << "\n Level " << level << ": Watch the arrow\n\n";
                showArrow(arrow);
                waitForEnter();
            }

            // Ask the player to repeat the sequence
            clearScreen();
            playerInput.clear();
            cout << "🔁 Repeat the sequence:\n";

            for (size_t i = 0; i < sequence.size(); ++i) {
                char input;
                bool valid = false;

                // Repeat until valid input is given
                do {
                    cout << "Arrow " << i + 1 << ": ";
                    cin >> input;
                    cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
                    input = toupper(input);
                    if (isValidKey(input)) {
                        valid = true;
                        playerInput.push_back(input);
                    } else {
                        cout << "⚠️ Invalid input! Please enter W, A, S, or D.\n";
                    }
                } while (!valid);
            }

            // Check if the player's input matches the sequence
            if (playerInput != sequence) {
                cout << "\n ❌ Incorrect! Game over at level " << level << ".\n";
                playing = false;
                player.score = level - 1;
            } else {
                cout << "\n ✅ Correct! Moving to level " << (++level) << "...\n";
                cout << "Press ENTER to continue...";
                cin.get(); // Waits for ENTER
            }
        }

        // End of game message
        cout << "\n✨ Thanks for playing, " << player.name << "!\n";
        cout << " Your final score: " << player.score << endl;

        // Save the player's score
        saveScore(player);
    }

} // namespace ClefairyGame

#endif // CLEAFIRYSAYS_H